version: "2"

services:
  postgres:
    image: postgres:9.6.5
    restart: ${RESTART}
    environment:
      - POSTGRES_DB=${dbname}
      - POSTGRES_USER=${dbuser}
      - POSTGRES_PASSWORD=${dbpassword}
    ports:
      - 5432:5432/tcp
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  postgres-vol:
    driver: local
