.catalog:
  name: Python
  version: 2.7-slim-jessie
  uuid: python-0
  questions:
  - variable: WORKDIR
    description: 'Python project working directory'
    label: 'Python Workdir:'
    required: true
    default: "~/"
    type: string

