version: "2"

services:
  minio:
    image: minio/minio:RELEASE.2018-04-27T23-33-52Z
    volumes:
     - minio-vol:/data
    ports:
     - "${MINIO_PORT}:9000"
    environment:
     MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
     MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    restart: "${RESTART}"

volumes:
  minio-vol:
    driver: local